# Docker Compose for PolicyPal with AI Service
version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: policypal-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: policypal
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - policypal-network

  # NestJS Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: policypal-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/policypal
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_EXPIRES_IN=24h
      - FRONTEND_URL=http://localhost:4200
      - AI_SERVICE_URL=http://ai-service:8000
    depends_on:
      - mongodb
      - ai-service
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - policypal-network

  # Python AI Service
  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: policypal-ai-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGODB_URI=mongodb://mongodb:27017/policypal_ai
      - AI_SERVICE_PORT=8000
      - AI_SERVICE_HOST=0.0.0.0
    depends_on:
      - mongodb
    volumes:
      - ./ai-service:/app
      - ai_uploads:/app/uploads
    networks:
      - policypal-network

  # Angular Frontend (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: policypal-frontend
    restart: unless-stopped
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - policypal-network

volumes:
  mongodb_data:
    driver: local
  ai_uploads:
    driver: local

networks:
  policypal-network:
    driver: bridge
